const defaultSEO = {
  keywords: [
    'iphone',
    'iphone sale',
    'buy iphone',
    'iphone store',
    'apple phones',
    'iphone deals',
    'iphone e-commerce',
    'iphone shopping',
    'apple store',
    'iphone marketplace',
    'new iphone',
    'refurbished iphone',
    'cheap iphone',
    'iphone discounts',
    'latest iphone',
    'online iphone store',
    'iphone shop',
    'iphone offers',
    'iphone products',
    'apple devices',
    'iphone models',
    'iphone accessories',
    'iphone purchase',
    'best iphone deals',
    'iphone online',
  ],
  image: '/images/preview-image.png',
  url: typeof window !== 'undefined' ? window.location.href : '',
  type: 'website',
};

export default defaultSEO;
